AWSTemplateFormatVersion: '2010-09-09'
Transform: 
  - AWS::SecretsManager-2020-07-23
Description: >-
    database-class-setup : SecretsManager secrets we'll use later to initialize our various database admins.

Parameters:

  Prefix:
    Type: String
    Default: database
    Description: "A Prefix to use on the resource names and exports (To ensure uniqueness)."

Resources:
  
  DBAdminSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Description: Secret for the database user and password
      # Auto-generate a 16 character password for a user named "dbadmin"
      # We use dbadmin because "admin" is a reserved word in many systems (Postgres, Documentdb)
      GenerateSecretString:
        SecretStringTemplate: '{"username":"dbadmin"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludePunctuation: true
        
Outputs:
    
  DBAdminSecretArn:
    Value: !Ref DBAdminSecret
    Export:
      Name: !Join ["-", [!Ref Prefix, "DBAdminSecretArn"]]    