AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  database-class-setup : Aurora Postgresql database cluster.
  
Parameters:

  Prefix:
    Description: "String used in resource names and exports to ensure uniqueness."
    Default: database
    Type: String

Resources:

  RDSClusterPg:
    Type: 'AWS::RDS::DBCluster'
    DeletionPolicy: Snapshot
    Properties:
      # NOTE: username and password are coming from the secret created earlier in this stack.
      # To make it even more complicated, the Secret was created in another stack so we are going to ImportValue of the Secret Arn
      MasterUsername:
        !Join 
          - ''
          - - '{{resolve:secretsmanager:'
            - Fn::ImportValue:
                !Join
                  - "-"
                  - - !Ref Prefix
                    - "DBAdminSecretArn"
            - ':SecretString:username}}'
      MasterUserPassword:
        !Join 
          - ''
          - - '{{resolve:secretsmanager:'
            - Fn::ImportValue:
                !Join
                  - "-"
                  - - !Ref Prefix
                    - "DBAdminSecretArn"
            - ':SecretString:password}}'
      Engine: aurora-postgresql
      # With Aurora - Version is set at the cluster level
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-engineversion
      # aws rds describe-db-engine-versions --engine aurora-postgresql --query "DBEngineVersions[].EngineVersion" 
      EngineVersion: 15.3
      # NOTE: Overriding the Aurora default of 3306 when using Provisioned (Mysql and Postgres!)
      Port: 5432
      DBSubnetGroupName:
        Fn::ImportValue: 
          !Join ["-", [!Ref Prefix, "DBSubnetGroup"]]
      VpcSecurityGroupIds:
        - Fn::ImportValue:
            !Join
              - "-"
              - - !Ref Prefix
                - "DBSecurityGroup"
      # https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/USER_LogAccess.Procedural.UploadtoCloudWatch.html
      EnableCloudwatchLogsExports:
        - postgresql
      # https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/UsingWithRDS.IAMDBAuth.html
      EnableIAMDatabaseAuthentication: true
      StorageEncrypted: true
      

  RDSDBParameterGroupPg:
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
      Description: 'DB Parameter Group'
      Family: aurora-postgresql15
      Parameters:
        max_connections: 1000
      
  RDSDBInstance01Pg:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: aurora-postgresql
      CACertificateIdentifier: rds-ca-rsa2048-g1
      DBClusterIdentifier: !Ref RDSClusterPg
      DBInstanceClass: db.r6g.large
      DBParameterGroupName: !Ref RDSDBParameterGroupPg
      DBSubnetGroupName:
        Fn::ImportValue: 
          !Join ["-", [!Ref Prefix, "DBSubnetGroup"]]
      EnablePerformanceInsights: true

  RDSDBInstance02Pg:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: aurora-postgresql
      CACertificateIdentifier: rds-ca-rsa2048-g1
      DBClusterIdentifier: !Ref RDSClusterPg
      DBInstanceClass: db.r6g.large
      DBParameterGroupName: !Ref RDSDBParameterGroupPg
      DBSubnetGroupName:
        Fn::ImportValue: 
          !Join ["-", [!Ref Prefix, "DBSubnetGroup"]]
      EnablePerformanceInsights: true  

Outputs:
   
  #
  # Postgresql cluster
  #

  RDSClusterNamePg:
    Value: !Ref RDSClusterPg
    Export:
      Name: !Join ["-", [ !Ref Prefix, "PostgresqlName"]]
      
  RDSClusterPortPg:
    Value: !GetAtt RDSClusterPg.Endpoint.Port
    Export:
      Name: !Join ["-", [ !Ref Prefix, "PostgresqlPort"]]
      
  RDSClusterEndpointPg:
    Value: !GetAtt RDSClusterPg.Endpoint.Address
    Export:
      Name: !Join ["-", [ !Ref Prefix, "PostgresqlEndpoint"]]
  
  RDSClusterReadEndpointPg:
    Value: !GetAtt RDSClusterPg.ReadEndpoint.Address
    Export:
      Name: !Join ["-", [ !Ref Prefix, "PostgresqlReadEndpoint"]]
