AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  database-class-setup : MySQL MultiAZ Instance (not a Multi-AZ Cluster).
  
Parameters:

  Prefix:
    Description: "String used in resource names and exports to ensure uniqueness."
    Default: database
    Type: String

Resources:

  MySqlInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      AllocatedStorage: '5'
      # Graviton!
      DBInstanceClass: db.t4g.medium
      CACertificateIdentifier: rds-ca-rsa2048-g1
      Engine: MySQL
      # aws rds describe-db-engine-versions --default-only --engine mysql --engine-version 8.0 --region us-east-1 --query '*[].{Engine:Engine,EngineVersion:EngineVersion}' --output text
      EngineVersion: 8.0.33
      MultiAZ: True
      DBSubnetGroupName:
        Fn::ImportValue: 
          !Join ["-", [!Ref Prefix, "DBSubnetGroup"]]
      VPCSecurityGroups:
        - Fn::ImportValue:
            !Join
              - "-"
              - - !Ref Prefix
                - "DBSecurityGroup"

      DBParameterGroupName: !Ref 'MySqlParamGroup'
       # NOTE: username and password are coming from the secret created earlier in this stack.
      # To make it even more complicated, the Secret was created in another stack so we are going to ImportValue of the Secret Arn
      MasterUsername:
        !Join 
          - ''
          - - '{{resolve:secretsmanager:'
            - Fn::ImportValue:
                !Join
                  - "-"
                  - - !Ref Prefix
                    - "DBAdminSecretArn"
            - ':SecretString:username}}'
      MasterUserPassword:
        !Join 
          - ''
          - - '{{resolve:secretsmanager:'
            - Fn::ImportValue:
                !Join
                  - "-"
                  - - !Ref Prefix
                    - "DBAdminSecretArn"
            - ':SecretString:password}}'
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-enablecloudwatchlogsexports
      EnableCloudwatchLogsExports:
        - audit
        - error
        - general
        - slowquery
      EnablePerformanceInsights: true
      EnableIAMDatabaseAuthentication: true
      StorageEncrypted: true
  
  MySqlParamGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Family: MySQL8.0
      Description: CloudFormation Sample Database Parameter Group
      Parameters:
        autocommit: '1'
        general_log: '1'
        
Outputs:

  #
  # MySql instance
  #
  
  MySqlInstance:
    Value: !Ref MySqlInstance
    Export:
      Name: !Join ["-", [ !Ref Prefix, "MySqlInstanceName"]]
      
  MySqlInstancePort:
    Value: !GetAtt MySqlInstance.Endpoint.Port
    Export:
      Name: !Join ["-", [ !Ref Prefix, "MySqlInstancePort"]]
      
  MySqlInstanceEndpoint:
    Value: !GetAtt MySqlInstance.Endpoint.Address
    Export:
      Name: !Join ["-", [ !Ref Prefix, "MySqlInstanceEndpoint"]]
