AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  database-class-setup : Aurora MySQL database cluster.
  
Parameters:

  Prefix:
    Description: "String used in resource names and exports to ensure uniqueness."
    Default: database
    Type: String

Resources:

  RDSCluster:
    Type: 'AWS::RDS::DBCluster'
    DeletionPolicy: Snapshot
    Properties:
      # NOTE: username and password are coming from the secret created earlier in this stack.
      # To make it even more complicated, the Secret was created in another stack so we are going to ImportValue of the Secret Arn
      MasterUsername:
        !Join 
          - ''
          - - '{{resolve:secretsmanager:'
            - Fn::ImportValue:
                !Join
                  - "-"
                  - - !Ref Prefix
                    - "DBAdminSecretArn"
            - ':SecretString:username}}'
      MasterUserPassword:
        !Join 
          - ''
          - - '{{resolve:secretsmanager:'
            - Fn::ImportValue:
                !Join
                  - "-"
                  - - !Ref Prefix
                    - "DBAdminSecretArn"
            - ':SecretString:password}}'
      Engine: aurora-mysql
      EngineMode: provisioned
      # With Aurora - Version is set at the cluster level
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-engineversion
      # aws rds describe-db-engine-versions --engine aurora-mysql --query "DBEngineVersions[].EngineVersion"
      EngineVersion: 8.0.mysql_aurora.3.04.0
      DBSubnetGroupName:
        Fn::ImportValue: 
          !Join ["-", [!Ref Prefix, "DBSubnetGroup"]]
      VpcSecurityGroupIds:
        - Fn::ImportValue:
            !Join
              - "-"
              - - !Ref Prefix
                - "DBSecurityGroup"
      EnableCloudwatchLogsExports:
        - audit
        - error
        - general
        - slowquery
      # https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/UsingWithRDS.IAMDBAuth.html
      EnableIAMDatabaseAuthentication: true
      StorageEncrypted: true
      # Backtrack enabled for 1 hour (Aurora MySQL only!)
      BacktrackWindow: 3600
      
                
  RDSDBClusterParameterGroup: 
    Type: "AWS::RDS::DBClusterParameterGroup"
    Properties: 
      Description: 'Cluster Parameter Group'
      # aws rds describe-db-engine-versions --query "DBEngineVersions[].DBParameterGroupFamily"
      Family: aurora-mysql8.0
      Parameters: 
        time_zone: US/Eastern
  
  RDSDBParameterGroup:
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
      Description: 'DB Parameter Group'
      Family: aurora-mysql8.0
      Parameters:
        sql_mode: IGNORE_SPACE
        innodb_buffer_pool_size: '{DBInstanceClassMemory*3/4}'
      
  RDSDBInstance01:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: aurora-mysql
      CACertificateIdentifier: rds-ca-rsa2048-g1
      # aws rds describe-db-engine-versions --default-only --engine mysql --engine-version 8.0 --region us-east-1 --query '*[].{Engine:Engine,EngineVersion:EngineVersion}' --output text
      DBClusterIdentifier: !Ref RDSCluster
      DBInstanceClass: db.r5.large
      DBParameterGroupName: !Ref RDSDBParameterGroup
      DBSubnetGroupName:
        Fn::ImportValue: 
          !Join ["-", [!Ref Prefix, "DBSubnetGroup"]]
      EnablePerformanceInsights: true

  RDSDBInstance02:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: aurora-mysql
      CACertificateIdentifier: rds-ca-rsa2048-g1
      DBClusterIdentifier: !Ref RDSCluster
      DBInstanceClass: db.r5.large
      DBParameterGroupName: !Ref RDSDBParameterGroup
      DBSubnetGroupName:
        Fn::ImportValue: 
          !Join ["-", [!Ref Prefix, "DBSubnetGroup"]]
      EnablePerformanceInsights: true

Outputs:

  #
  # MySql cluster
  #
  
  RDSClusterName:
    Value: !Ref RDSCluster
    Export:
      Name: !Join ["-", [ !Ref Prefix, "MySqlName"]]
      
  RDSClusterPort:
    Value: !GetAtt RDSCluster.Endpoint.Port
    Export:
      Name: !Join ["-", [ !Ref Prefix, "MySqlPort"]]
      
  RDSClusterEndpoint:
    Value: !GetAtt RDSCluster.Endpoint.Address
    Export:
      Name: !Join ["-", [ !Ref Prefix, "MySqlEndpoint"]]
  
  RDSClusterReadEndpoint:
    Value: !GetAtt RDSCluster.ReadEndpoint.Address
    Export:
      Name: !Join ["-", [ !Ref Prefix, "MySqlReadEndpoint"]]
      